[package]
name = "gblite"
version = "0.1.1"
authors = ["Austin Lasher <austin@lasher.email>"]
edition = "2018"

[dependencies]
libgblite = { path = "../libgblite" }
ctrlc = { version = "3.1.*", features = ["termination"] }